# set max velocity [v_x, v_y, v_rz] units [m/s, m/s, rad/s]
bool set_velocity_max
float64[3] velocity_max

# set leg length
bool set_leg_length
float64 leg_length

# set step clearance
bool set_step_clearance
float64 step_clearance

# set obstical avoidence
bool set_avoid_obstacles
bool avoid_obstacles

# set obstacle_threshold
bool set_obstacle_threshold
float64 obstacle_threshold

bool set_feet_avoid_unsteppable_regions
bool feet_avoid_unsteppable_regions

bool set_feet_match_terrain
bool feet_match_terrain


# TODO: String list and float list to make it easier to use
