# goal
geometry_msgs/PoseStamped    target
string target_object 
bool set_position_tolerance
float64 position_tolerance
digit_msgs/MobilityParameters mobility_parameters
---
# result
bool success
---
# feedback
